import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardLayout from "./dashboard/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-inter`}
      >
        <ClerkProvider>
          <Show when="signed-out">
            <div className="flex justify-center items-center min-h-screen gap-4">
              <SignInButton />
              <SignUpButton />
            </div>
          </Show>

          <Show when="signed-in">
            <div className="w-full h-14 flex justify-between items-center">
              <p>Quiz app</p>
              <UserButton />
            </div>
            <DashboardLayout children={children} />
          </Show>
        </ClerkProvider>
      </body>
    </html>
  );
}
