import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardLayout from "./dashboard/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Show when="signed-out">
            <div className="flex justify-center items-center min-h-screen gap-4">
              <SignInButton />
              <SignUpButton />
            </div>
          </Show>

          <Show when="signed-in">
            {/* STICKY NAVBAR */}
            <header className="fixed top-0 left-0 right-0 h-16 border-b bg-white flex justify-between items-center px-6 z-50">
              <div className="flex items-center gap-4">
                <p className="font-bold">Quiz app</p>
              </div>
              <UserButton />
            </header>

            {/* MAIN CONTENT AREA */}
            <div className="pt-16">
              {" "}
              {/* Padding top to prevent content hiding under header */}
              <DashboardLayout>{children}</DashboardLayout>
            </div>
          </Show>
        </body>
      </html>
    </ClerkProvider>
  );
}
